spring:
    application:
      name: shatding-springboot-mybatis
    shardingsphere:
      props:
        sql.show: true
      datasource:
        names: ds2
        # 数据源ds2
        ds2:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
        # url: jdbc:mysql://localhost:3306/test_order2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          url: jdbc:mysql://localhost:3307/test_order2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          username: root
          password: HSJissmart1
      sharding:
          defaultDataSourceName: ds2
          tables:
            t_user:  #t_user表
              key-generator-column-name: id  #主键
              actual-data-nodes: ds2.t_user${0..5}    #数据节点,均匀分布
              table-strategy:  #分表策略
                inline: #行表达式
                  sharding-column: id
                  algorithm-expression: t_user${id % 6} #5. inline表达式返回结果为何出现浮点数？回答：Java的整数相除结果是整数，但是对于inline表达式中的Groovy语法则不同，整数相除结果是浮点数。 想获得除法整数结果需要将A/B改为A.intdiv(B)。